INSERT INTO `plant_data` (`plant_id`, `temp`, `created_at`, `updated_at`) VALUES 
    (1, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);