INSERT INTO `plant_air_humidities` (`plant_id`, `umid_atm`, `created_at`, `updated_at`) VALUES 
    (1, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);