INSERT INTO `plant_soil_moistures` (`plant_id`, `umid_sol`, `created_at`, `updated_at`) VALUES 
    (1, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);